
map $uri $supabase_apikey {
  default "#{SUPABASE_APIKEY}#";
}

server {
  listen 80;
  listen [::]:80;
  server_name #{SUB_DOMAIN}#.#{DOMAIN}#;


  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Referrer-Policy "no-referrer-when-downgrade" always;

  location / {
    root /data/www;
    index index.html;
  }

  location /measurement_units {
    rewrite ^/measurement_units(.*)$ /unidades_medida$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /products {
    rewrite ^/products(.*)$ /productos$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /categories {
    rewrite ^/categories(.*)$ /categorias$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /brand {
    rewrite ^/brand(.*)$ /marcas$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /presentation {
    rewrite ^/presentation(.*)$ /presentaciones$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /price_history {
    rewrite ^/price_history(.*)$ /precios_historicos$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /stores {
    rewrite ^/stores(.*)$ /tiendas$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /login {
    rewrite ^/login(.*)$ /token$1 break;
    proxy_pass #{SUPABASE_DOMAIN}#;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }

  location /signup {
    proxy_pass #{SUPABASE_DOMAIN}#/signup;
    include /etc/nginx/snippets/supabase-proxy.conf;
  }
}
